# Generated by Django 3.1.1 on 2020-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='state',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
